name: terraform-fmt-check

on: [push]

jobs:
  terraform-fmt-check:
    runs-on: ubuntu-latest
    name: terraform-fmt-check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        id: fmt-check
        with:
          path: terraform

      - name: Wrong formatting found
        if: ${{ failure() && steps.fmt-check.outputs.failure-reason == 'check-failed' }}
        run: echo "terraform formatting check failed"
